- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql55
   - mysql55-libs
   - mysql55-server
   - mysql55-devel
   - MySQL-python27 
  tags: mysql

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
   - restart mysql
  tags: mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  tags: mysql

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mysql


- name: delete anonymous MySQL server user 
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
  tags: mysql

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" host="localhost" state="absent"
  tags: mysql

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  tags: mysql

- name: create database
  mysql_db: db={{ mt.db.name }} state=present encoding=utf8
  tags: mysql

- name: create database user
  mysql_user: name={{ mt.db.user }} password="{{ mt.db.passwd }}" priv={{ mt.db.name }}.*:ALL state=present
  tags: mysql

- name: mysqlbackup
  template: src=mysqlbackup.sh.j2 dest=/usr/local/bin/mysqlbackup.sh owner=root group=root mode=0755
  tags: mysql

- name: crontab mysqlbackup
  cron: name='mysqlbackup' job="/usr/bin/setlock -nx /tmp/mysqlbackup.lock /usr/local/bin/mysqlbackup.sh" hour="5" minute="0" user="root" state=present
  when: dbbackup == 'ON'
  tags: mysql
