- name: copy MT.zip
  unarchive: src="{{mt.file}}" dest=/var/www/ owner=apache group=contents mode=0775 creates=/var/www/movabletype/
  tags: movabletype

- name: Move movabletype to mt
  command: mv /var/www/{{mt.ver}} /var/www/movabletype creates=/var/www/movabletype/
  tags: movabletype

- name: Install the mt-plugins
  copy: src="mt-plugins/{{ item }}" dest="/var/www/movabletype/plugins/" owner=apache group=contents mode=0775
  when: mt.plugins is defined
  with_items:
    - "{{ mt.plugins }}"
  tags: movabletype

- name: Install the mt-static
  copy: src="mt-static/{{ item }}" dest="/var/www/movabletype/mt-static/" owner=apache group=contents mode=0775
  when: mt.static is defined
  with_items:
    - "{{ mt.static }}"
  tags: movabletype

- name: replace mt-config
  template: src=mt-config.cgi.j2 dest=/var/www/movabletype/mt-config.cgi owner=apache group=contents mode=0775
  tags: movabletype

- name: check service
  shell: stat /service/movabletype 
  ignore_errors: True
  register: result_service_mt
  tags: movabletype

- name: addsv movabletype
  shell: /usr/local/bin/addsv.sh movabletype
  when: mt.psgi == 'ON' and result_service_mt|failed
  tags: movabletype

- name: replace run
  replace: >-
    dest='/service/.movabletype/run'
    regexp='^sleep 3$'
    replace='{{ runfile }}'
  when: mt.psgi == 'ON' and result_service_mt|failed
  tags: movabletype

- name: Move .movabletype to movabletype
  command: creates="/service/movabletype" mv /service/.movabletype /service/movabletype
  when: mt.psgi == 'ON'
  tags: movabletype

- name: set run-periodic-tasks
  cron: name='run-periodic-tasks' job="cd /var/www/movabletype/; /usr/bin/setlock -nx /tmp/run-periodic-tasks.lock ./tools/run-periodic-tasks" minute="*/5" user="apache" state=present
  tags: movabletype

# pip passlibに依存
- name: create htpasswd
  htpasswd: path=/var/www/movabletype/basic_passwd name={{  mt.basic.user }} password={{ mt.basic.passwd }} owner=apache group={{shared_group}} mode=0644
  tags: movabletype

- name: restart mt
  command: /usr/bin/svc -du /service/movabletype
  when: mt.psgi == 'ON'
  tags: movabletype

- name: logrotate
  template: src=logrotate.d.mt.j2 dest=/etc/logrotate.d/movabletype owner=root group=root mode=0664
  tags: logrotate

