---
# ImageMagick
- name: ImageMagick is installed
  yum: name={{ item }} state=present
  with_items:
   - ImageMagick-c++
   - ImageMagick-c++-devel
   - ImageMagick-devel
   - ImageMagick-perl
   - compat-ImageMagick
  tags: ImageMagick

- name: insert "Policymap" configuation block in /etc/ImageMagick/policy.xml
  blockinfile:
    dest: /etc/ImageMagick/policy.xml
    block: "{{ policymap }}"
  tags: ImageMagick

