---
# httpd
- name: install the latest version of Apache
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - httpd-devel
  tags: httpd

- name: replace httpd.conf servername
  replace: dest="/etc/httpd/conf/httpd.conf" regexp="{{ item.regexp }}" replace="{{ item.replace }}" 
  with_items: httpd_conf
 tags: httpd

- name: check sysconfig/httpd
  shell: grep 'umask 002' /etc/sysconfig/httpd
  ignore_errors: True
  register: result_sysconfig_httpd
  tags: httpd

- name: replace sysconfig/httpd
  shell: echo "umask 002" >> /etc/sysconfig/httpd
  tags:  httpd
  when: result_sysconfig_httpd|failed

- name: Create Apache configuration file 00
  template: src=00.setting.conf.j2 dest=/etc/httpd/conf.d/00.setting.conf
  tags: httpd

- name: Create vhost.dummy configuration file 01
  template: src=01.dummy.conf.j2 dest=/etc/httpd/conf.d/01.dummy.conf
  tags: httpd

- name: Create ssl configuration file 02
  template: src=02.ssl.conf.j2 dest=/etc/httpd/conf.d/02.ssl.conf
  tags: httpd

- name: Create Apache configuration file vhosts
  template: src=vhosts.conf.j2 dest=/etc/httpd/conf.d/{{ item.name }}.conf
  with_items: vhosts
  tags: httpd

- name: httpd vhosts directory
  file: path=/var/www/vhosts/{{ item.name }}/ state=directory owner=apache group={{ shared_group }} mode=0775
  with_items: vhosts
  tags: httpd

- name: change owner
  file: path=/var/www/vhosts owner=root group=root mode=0755
  tags: httpd

- name: httpd vhosts cgi-bin
  file: path=/var/www/vhosts/{{ item.name }}/cgi-bin/ state=directory owner=apache group={{ shared_group }} mode=0775
  with_items: vhosts
  tags: httpd

- name: httpd vhosts htdocs
  file: path=/var/www/vhosts/{{ item.name }}/htdocs/ state=directory owner=apache group={{ shared_group }} mode=0775
  with_items: vhosts
  tags: httpd

- name: httpd vhosts logs
  file: path=/var/www/vhosts/{{ item.name }}/logs/ state=directory owner=apache group={{ shared_group }} mode=0775
  with_items: vhosts
  tags: httpd

- name: delete ssl_conf
  file: path=/etc/httpd/conf.d/{{item}} state=absent
  with_items:
    - ssl.conf
    - README
    - welcome.conf
  tags: httpd

- name: compress the log
  cron: name='logrotate' job="find /var/www/vhosts/*/logs/ -type f ! -name "*`date +%Y%m%d`*" ! -name "*.gz" -print0 | xargs -0 gzip 1>/dev/null" minute=0 hour=1 state=present
  tags: httpd

- name: delete the log
  cron: name='logrotate' job="find /var/www/vhosts/*/logs/ -type f -name '*.gz' -mtime +31 -print0 | xargs -0 rm -rf 1>/dev/null" minute=5 hour=1 state=present
  tags: httpd

- name: httpd is runnning and enabled
  service: name=httpd state=running enabled=yes
  tags: httpd

