- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install the latest libraries
  yum: name={{ item }} state=present
  with_items: packages
  tags: package

- name: yum update
  yum: state=latest name=*
  tags: package

- name: remove the sendmail package
  yum: name=sendmail state=absent
  tags: sendmail

- name: set locale to /etc/sysconfig/i18n
  replace: >
    dest=/etc/sysconfig/i18n
    regexp='^LANG=en_US\.UTF-8'
    replace='LANG={{locale}}'
  tags: locale

- name: set zone to /etc/sysconfig/clock
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^ZyesE=\"UTC\"'
    replace='ZyesE="{{zone}}"'
  tags: locale

- name: set false to clock utc
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^UTC=true'
    replace='UTC=false'
  tags: locale

- name: set jp localtime
  file: >
    src={{zoneinfo_path}}
    dest=/etc/localtime
    state=link
    force=yes
  tags: locale

- name: set path to ldconfig
  template: src=usr_local.conf.j2 dest=/etc/ld.so.conf.d/usr_local.conf
  tags: ldconfig

- name: set hostname
  hostname: name={{server_hostname}}
  tags: hostname

- name: set hostname to current ansible name
  action: command hostname {{server_hostname}}
  tags: hostname

- name: set forward
  template: src=forward.j2 dest=/root/.forward
  tags: forward

- name: postifx is runnning and enabled
  service: name=postfix state=running enabled=yes
  tags: postfix
